---
title: "WLS"
output: html_document
date: "2024-04-28"
---

# Feasible OLS estimator -> motivates using WLS

Note: emp_aff_math_biz_cl (3020x93)

```{r}
# Remove NA's in covariate columns or else WLS won't run accurately (use 3020 rows)
emp_aff_math_biz_cl <- emp_aff_math_biz[complete.cases(emp_aff_math_biz[, c("emp", "revenue_all","spend_all","engagement","merchants_all")]), ]
```


```{r}
# Fit the initial OLS model
ols.fit <- lm(revenue_all ~ wave1 + emp + spend_all + engagement + merchants_all + NE + W + S, data = emp_aff_math_biz_cl)

# Create a new dataframe to hold residuals
dat.res <- emp_aff_math_biz_cl
# Log transformation of the squared residuals; ensure you square the residuals first then take the log
dat.res$residuals_transformed <- log((ols.fit$residuals)^2)

# Fit another OLS model on the transformed residuals in the new dataframe
t.res.ols <- lm(residuals_transformed ~ wave1 + emp + spend_all + engagement + merchants_all + NE + W + S, data = dat.res)

# Calculate weights for FGLS
w.fgls <- exp(-t.res.ols$fitted.values)

# Fit the FGLS model using the original response variable and the calculated weights
fgls.fit <- lm(revenue_all ~ wave1 + emp + spend_all + engagement + merchants_all + NE + W + S, 
                       weights = w.fgls, data = emp_aff_math_biz_cl)

# Compare the coefficients of the initial OLS model and the FGLS model
round(summary(ols.fit)$coef, 3)
round(summary(fgls.fit)$coef, 3)
```

# WLS with full model 1

```{r}
# Fit the OLS model and handle NAs if they are present
full_model1 <- lm(revenue_all ~ wave1 + emp + spend_all + engagement + merchants_all + NE + W + S, data = emp_aff_math_biz_cl)

resid <- residuals(full_model1)

# Calculate the weights 
sqr_weights <- 1 / (sqrt(abs(resid)) + 1e-6) # weight transformation
#weights <- 1 / (resid^2 + 1e-6)

# Fit the WLS model using the weights
wls_model <- lm(revenue_all ~ wave1 + emp + spend_all + engagement + merchants_all + NE + W + S, data = emp_aff_math_biz_cl, weights = sqr_weights)
summary(wls_model)
summary(full_model1)
```

```{r}
plot(wls_model)
vif(wls_model)
```

```{r}
plot(full_model1)
vif(full_model1)
```

QQ plot better with WLS
- Even though the residuals vs. fitted plots might look similar for both models, the QQ plot could reveal that the variance of residuals across the range of fitted values is more consistent in the WLS model.



